// <auto-generated />
using System;
using Instagram.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Instagram.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Instagram.Infrastructure.Data.Models.Follower", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Followers");

                    b.HasData(
                        new
                        {
                            Id = "follow-01-a81f",
                            CreatedAt = new DateTime(2025, 1, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902",
                            FollowingId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "follow-02-b19f",
                            CreatedAt = new DateTime(2025, 1, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903",
                            FollowingId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "follow-03-c7fa",
                            CreatedAt = new DateTime(2025, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "c91e9189-281f-48c3-b8ad-1b20f4f10104",
                            FollowingId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902"
                        },
                        new
                        {
                            Id = "follow-04-d812",
                            CreatedAt = new DateTime(2025, 1, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105",
                            FollowingId = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903"
                        },
                        new
                        {
                            Id = "follow-05-e811",
                            CreatedAt = new DateTime(2025, 1, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106",
                            FollowingId = "e38db6c0-7b92-4f0f-b76a-d7b7f1aab107"
                        },
                        new
                        {
                            Id = "follow-06-f211",
                            CreatedAt = new DateTime(2025, 1, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108",
                            FollowingId = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109"
                        },
                        new
                        {
                            Id = "follow-07-911a",
                            CreatedAt = new DateTime(2025, 1, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110",
                            FollowingId = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111"
                        },
                        new
                        {
                            Id = "follow-08-71ab",
                            CreatedAt = new DateTime(2025, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "2df3b7c4-29c2-41b2-b2cb-51c8f20d8112",
                            FollowingId = "4b46a84d-21a3-44db-9d2f-68c2f51f3113"
                        },
                        new
                        {
                            Id = "follow-09-2f81",
                            CreatedAt = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116",
                            FollowingId = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115"
                        },
                        new
                        {
                            Id = "follow-10-91af",
                            CreatedAt = new DateTime(2025, 1, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "bbcfb1c7-d4a6-46fa-a9cc-5c9df8d07117",
                            FollowingId = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118"
                        },
                        new
                        {
                            Id = "follow-11-acde",
                            CreatedAt = new DateTime(2025, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01",
                            FollowingId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902"
                        },
                        new
                        {
                            Id = "follow-12-acde",
                            CreatedAt = new DateTime(2025, 1, 12, 9, 30, 0, 0, DateTimeKind.Utc),
                            FollowerId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01",
                            FollowingId = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903"
                        },
                        new
                        {
                            Id = "follow-13-acde",
                            CreatedAt = new DateTime(2025, 1, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902",
                            FollowingId = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105"
                        },
                        new
                        {
                            Id = "follow-14-acde",
                            CreatedAt = new DateTime(2025, 1, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903",
                            FollowingId = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106"
                        },
                        new
                        {
                            Id = "follow-15-acde",
                            CreatedAt = new DateTime(2025, 1, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109",
                            FollowingId = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110"
                        },
                        new
                        {
                            Id = "follow-16-acde",
                            CreatedAt = new DateTime(2025, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115",
                            FollowingId = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116"
                        },
                        new
                        {
                            Id = "follow-17-acde",
                            CreatedAt = new DateTime(2025, 1, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118",
                            FollowingId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "follow-18-acde",
                            CreatedAt = new DateTime(2025, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "bbcfb1c7-d4a6-46fa-a9cc-5c9df8d07117",
                            FollowingId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902"
                        },
                        new
                        {
                            Id = "follow-19-acde",
                            CreatedAt = new DateTime(2025, 1, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108",
                            FollowingId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "follow-20-acde",
                            CreatedAt = new DateTime(2025, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            FollowerId = "2df3b7c4-29c2-41b2-b2cb-51c8f20d8112",
                            FollowingId = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115"
                        });
                });

            modelBuilder.Entity("Instagram.Infrastructure.Data.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("ReciverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = "msg-001-4a8f1b01",
                            Content = "Hey, did you finish the API changes?",
                            CreatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "msg-002-92bc1102",
                            Content = "Almost, just fixing validation.",
                            CreatedAt = new DateTime(2026, 1, 1, 9, 2, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902"
                        },
                        new
                        {
                            Id = "msg-003-ff21ac03",
                            Content = "Nice, ping me when ready.",
                            CreatedAt = new DateTime(2026, 1, 1, 9, 3, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "msg-004-bac91204",
                            Content = "Can you review my UI mockups?",
                            CreatedAt = new DateTime(2026, 1, 1, 11, 10, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903"
                        },
                        new
                        {
                            Id = "msg-005-acde3305",
                            Content = "Sure, send them.",
                            CreatedAt = new DateTime(2026, 1, 1, 11, 12, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105"
                        },
                        new
                        {
                            Id = "msg-006-219fa006",
                            Content = "Using Docker Compose?",
                            CreatedAt = new DateTime(2026, 1, 2, 8, 30, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106"
                        },
                        new
                        {
                            Id = "msg-007-77cbe007",
                            Content = "Yes, makes networking easier.",
                            CreatedAt = new DateTime(2026, 1, 2, 8, 33, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "e38db6c0-7b92-4f0f-b76a-d7b7f1aab107"
                        },
                        new
                        {
                            Id = "msg-008-19aa2008",
                            Content = "Loved your last blog post.",
                            CreatedAt = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108"
                        },
                        new
                        {
                            Id = "msg-009-b211c009",
                            Content = "Thanks a lot!",
                            CreatedAt = new DateTime(2026, 1, 2, 12, 2, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109"
                        },
                        new
                        {
                            Id = "msg-010-a88cc010",
                            Content = "How do you track analytics?",
                            CreatedAt = new DateTime(2026, 1, 3, 9, 30, 0, 0, DateTimeKind.Utc),
                            Read = false,
                            ReciverId = "",
                            SenderId = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110"
                        },
                        new
                        {
                            Id = "msg-011-acde1011",
                            Content = "Mostly Firebase and custom events.",
                            CreatedAt = new DateTime(2026, 1, 3, 9, 32, 0, 0, DateTimeKind.Utc),
                            Read = false,
                            ReciverId = "",
                            SenderId = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111"
                        },
                        new
                        {
                            Id = "msg-012-acde1012",
                            Content = "QA found a bug in checkout.",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 10, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "2df3b7c4-29c2-41b2-b2cb-51c8f20d8112"
                        },
                        new
                        {
                            Id = "msg-013-acde1013",
                            Content = "Thanks, I’ll fix it today.",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 12, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "4b46a84d-21a3-44db-9d2f-68c2f51f3113"
                        },
                        new
                        {
                            Id = "msg-014-acde1014",
                            Content = "Any cloud provider recommendations?",
                            CreatedAt = new DateTime(2026, 1, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "5d7e09fa-b71a-44c5-9e1f-9b4e4b09f114"
                        },
                        new
                        {
                            Id = "msg-015-acde1015",
                            Content = "Azure is solid for .NET.",
                            CreatedAt = new DateTime(2026, 1, 4, 8, 2, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116"
                        },
                        new
                        {
                            Id = "msg-016-acde1016",
                            Content = "Meeting moved to tomorrow.",
                            CreatedAt = new DateTime(2026, 1, 4, 15, 20, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115"
                        },
                        new
                        {
                            Id = "msg-017-acde1017",
                            Content = "Got it, thanks.",
                            CreatedAt = new DateTime(2026, 1, 4, 15, 22, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "bbcfb1c7-d4a6-46fa-a9cc-5c9df8d07117"
                        },
                        new
                        {
                            Id = "msg-018-acde1018",
                            Content = "Want to discuss the startup idea?",
                            CreatedAt = new DateTime(2026, 1, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Read = false,
                            ReciverId = "",
                            SenderId = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118"
                        },
                        new
                        {
                            Id = "msg-019-acde1019",
                            Content = "Yes, let’s do it later today.",
                            CreatedAt = new DateTime(2026, 1, 5, 10, 5, 0, 0, DateTimeKind.Utc),
                            Read = false,
                            ReciverId = "",
                            SenderId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "msg-020-acde1020",
                            Content = "Can you help me with React hooks?",
                            CreatedAt = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108"
                        },
                        new
                        {
                            Id = "msg-021-acde1021",
                            Content = "Sure, what part?",
                            CreatedAt = new DateTime(2026, 1, 6, 9, 1, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902"
                        },
                        new
                        {
                            Id = "msg-022-acde1022",
                            Content = "useEffect dependencies confuse me.",
                            CreatedAt = new DateTime(2026, 1, 6, 9, 3, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108"
                        },
                        new
                        {
                            Id = "msg-023-acde1023",
                            Content = "They control when the effect runs.",
                            CreatedAt = new DateTime(2026, 1, 6, 9, 5, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902"
                        },
                        new
                        {
                            Id = "msg-024-acde1024",
                            Content = "Ahh that helps a lot.",
                            CreatedAt = new DateTime(2026, 1, 6, 9, 6, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108"
                        },
                        new
                        {
                            Id = "msg-025-acde1025",
                            Content = "Security scan passed.",
                            CreatedAt = new DateTime(2026, 1, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "c91e9189-281f-48c3-b8ad-1b20f4f10104"
                        },
                        new
                        {
                            Id = "msg-026-acde1026",
                            Content = "Great news!",
                            CreatedAt = new DateTime(2026, 1, 7, 10, 1, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106"
                        },
                        new
                        {
                            Id = "msg-027-acde1027",
                            Content = "Want to test the beta build?",
                            CreatedAt = new DateTime(2026, 1, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "e38db6c0-7b92-4f0f-b76a-d7b7f1aab107"
                        },
                        new
                        {
                            Id = "msg-028-acde1028",
                            Content = "Sure, send the link.",
                            CreatedAt = new DateTime(2026, 1, 8, 14, 1, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111"
                        },
                        new
                        {
                            Id = "msg-029-acde1029",
                            Content = "Presentation slides ready.",
                            CreatedAt = new DateTime(2026, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110"
                        },
                        new
                        {
                            Id = "msg-030-acde1030",
                            Content = "Perfect, thanks.",
                            CreatedAt = new DateTime(2026, 1, 9, 9, 2, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115"
                        },
                        new
                        {
                            Id = "msg-031-acde1031",
                            Content = "Java service deployed.",
                            CreatedAt = new DateTime(2026, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "4b46a84d-21a3-44db-9d2f-68c2f51f3113"
                        },
                        new
                        {
                            Id = "msg-032-acde1032",
                            Content = "Monitoring looks good.",
                            CreatedAt = new DateTime(2026, 1, 10, 11, 5, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116"
                        },
                        new
                        {
                            Id = "msg-033-acde1033",
                            Content = "Smart contract deployed.",
                            CreatedAt = new DateTime(2026, 1, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "5d7e09fa-b71a-44c5-9e1f-9b4e4b09f114"
                        },
                        new
                        {
                            Id = "msg-034-acde1034",
                            Content = "Awesome work.",
                            CreatedAt = new DateTime(2026, 1, 11, 13, 2, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118"
                        },
                        new
                        {
                            Id = "msg-035-acde1035",
                            Content = "Interviews scheduled.",
                            CreatedAt = new DateTime(2026, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "bbcfb1c7-d4a6-46fa-a9cc-5c9df8d07117"
                        },
                        new
                        {
                            Id = "msg-036-acde1036",
                            Content = "Thanks for the update.",
                            CreatedAt = new DateTime(2026, 1, 12, 10, 1, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115"
                        },
                        new
                        {
                            Id = "msg-037-acde1037",
                            Content = "Want to co-author an article?",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            Read = false,
                            ReciverId = "",
                            SenderId = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109"
                        },
                        new
                        {
                            Id = "msg-038-acde1038",
                            Content = "Yes, sounds great.",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 5, 0, 0, DateTimeKind.Utc),
                            Read = false,
                            ReciverId = "",
                            SenderId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "msg-039-acde1039",
                            Content = "Your design tips helped!",
                            CreatedAt = new DateTime(2026, 1, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108"
                        },
                        new
                        {
                            Id = "msg-040-acde1040",
                            Content = "Happy to hear that 😊",
                            CreatedAt = new DateTime(2026, 1, 14, 9, 2, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903"
                        },
                        new
                        {
                            Id = "msg-041-acde1041",
                            Content = "Artwork campaign looks great.",
                            CreatedAt = new DateTime(2026, 1, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110"
                        },
                        new
                        {
                            Id = "msg-042-acde1042",
                            Content = "Thanks! Glad you liked it.",
                            CreatedAt = new DateTime(2026, 1, 15, 11, 2, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105"
                        },
                        new
                        {
                            Id = "msg-043-acde1043",
                            Content = "Mobile build ready for testing.",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111"
                        },
                        new
                        {
                            Id = "msg-044-acde1044",
                            Content = "I’ll test it tonight.",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 5, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "msg-045-acde1045",
                            Content = "Logs look clean.",
                            CreatedAt = new DateTime(2026, 1, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116"
                        },
                        new
                        {
                            Id = "msg-046-acde1046",
                            Content = "Great 👍",
                            CreatedAt = new DateTime(2026, 1, 17, 10, 1, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106"
                        },
                        new
                        {
                            Id = "msg-047-acde1047",
                            Content = "Roadmap approved.",
                            CreatedAt = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115"
                        },
                        new
                        {
                            Id = "msg-048-acde1048",
                            Content = "Perfect, let’s move forward.",
                            CreatedAt = new DateTime(2026, 1, 18, 9, 2, 0, 0, DateTimeKind.Utc),
                            Read = true,
                            ReciverId = "",
                            SenderId = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118"
                        },
                        new
                        {
                            Id = "msg-049-acde1049",
                            Content = "Publishing tomorrow.",
                            CreatedAt = new DateTime(2026, 1, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            Read = false,
                            ReciverId = "",
                            SenderId = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109"
                        },
                        new
                        {
                            Id = "msg-050-acde1050",
                            Content = "Great timing.",
                            CreatedAt = new DateTime(2026, 1, 19, 14, 1, 0, 0, DateTimeKind.Utc),
                            Read = false,
                            ReciverId = "",
                            SenderId = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110"
                        });
                });

            modelBuilder.Entity("Instagram.Infrastructure.Data.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "post-01-9f1b4d8a-21c0-4f5c-b102-a001",
                            Content = "Started rebuilding my backend architecture today.",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-02-7c2a5d11-2e90-4bcb-a901-a002",
                            Content = "React hooks finally make sense.",
                            CreatedAt = new DateTime(2026, 1, 1, 9, 15, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-03-b81a7a29-0b8c-4a3b-b621-a003",
                            Content = "Designing a fresh dark theme UI 🌙",
                            CreatedAt = new DateTime(2026, 1, 1, 10, 40, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/3.jpg",
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-04-21f7ac19-91c2-48bb-b812-a004",
                            Content = "Learning penetration testing basics.",
                            CreatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-05-3d71a8b4-7731-4b42-93b2-a005",
                            Content = "New illustration finished today 🎨",
                            CreatedAt = new DateTime(2026, 1, 1, 13, 25, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/5.jpg",
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-06-41bc8c90-d241-4aa4-9921-a006",
                            Content = "Docker containers saved my sanity.",
                            CreatedAt = new DateTime(2026, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-07-19f7d901-8f62-4b98-8211-a007",
                            Content = "Experimenting with game physics today.",
                            CreatedAt = new DateTime(2026, 1, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/7.jpg",
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-08-771a9d44-6f11-4d55-b341-a008",
                            Content = "Exams week again 😭",
                            CreatedAt = new DateTime(2026, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-09-5a6a7b28-3810-4d6a-9c81-a009",
                            Content = "Publishing my next tech article soon.",
                            CreatedAt = new DateTime(2026, 1, 2, 13, 45, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/9.jpg",
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-10-9912a83a-2489-4f7b-9a31-a010",
                            Content = "Analytics dashboards are addictive.",
                            CreatedAt = new DateTime(2026, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-11-84b7d312-fb20-41ad-9012-a011",
                            Content = "Mobile app memory usage finally optimized.",
                            CreatedAt = new DateTime(2026, 1, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-12-27b7f981-21a0-4db6-81f1-a012",
                            Content = "QA automation saves weeks of work.",
                            CreatedAt = new DateTime(2026, 1, 3, 10, 10, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-13-fbc38d22-7b2a-4c51-a819-a013",
                            Content = "Java memory tuning is underrated.",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 40, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-14-91d72d19-2ab0-4e18-9f10-a014",
                            Content = "Reading about smart contracts today.",
                            CreatedAt = new DateTime(2026, 1, 3, 13, 20, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-15-31aa20fa-1e0c-4a4f-902a-a015",
                            Content = "Sprint planning done ✔️",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-16-ff2b91d0-7e42-46ad-a0f9-a016",
                            Content = "Cloud cost optimization is painful.",
                            CreatedAt = new DateTime(2026, 1, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-17-62cbd91a-f61e-4ef7-93fa-a017",
                            Content = "Hiring developers is harder than coding.",
                            CreatedAt = new DateTime(2026, 1, 4, 10, 30, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-18-1187a1df-4f42-4b02-b1f2-a018",
                            Content = "Pitch deck is almost ready 🚀",
                            CreatedAt = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-19-bc72fa01-3b22-4a83-9b41-a019",
                            Content = "JWT refresh tokens implemented.",
                            CreatedAt = new DateTime(2026, 1, 5, 9, 10, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-20-8c29f21a-5b81-47f2-a90c-a020",
                            Content = "Finally mastered CSS grid.",
                            CreatedAt = new DateTime(2026, 1, 5, 10, 45, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-21-37c29fa1-6e41-4012-a2b2-a021",
                            Content = "Minimal UI beats flashy UI.",
                            CreatedAt = new DateTime(2026, 1, 5, 12, 20, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-22-d31a8a41-ef02-42f7-8c3a-a022",
                            Content = "Sketching ideas for next artwork.",
                            CreatedAt = new DateTime(2026, 1, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/22.jpg",
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-23-51c9b122-19fa-48e3-8db1-a023",
                            Content = "CI/CD pipelines should be boring.",
                            CreatedAt = new DateTime(2026, 1, 5, 16, 10, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-24-1a8f7e21-d22b-4c4e-a190-a024",
                            Content = "Procedural terrain generation test.",
                            CreatedAt = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/24.jpg",
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-25-91c2df11-cc81-41fa-94b2-a025",
                            Content = "Coffee count today: 5 ☕",
                            CreatedAt = new DateTime(2026, 1, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-26-62adf91b-421a-421f-b912-a026",
                            Content = "Tech blogging consistency is hard.",
                            CreatedAt = new DateTime(2026, 1, 6, 13, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-27-9a81df21-1910-4d41-a401-a027",
                            Content = "Conversion metrics improved by 12%.",
                            CreatedAt = new DateTime(2026, 1, 6, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-28-2bc81df9-81fa-4f10-bd91-a028",
                            Content = "Flutter vs React Native debate continues.",
                            CreatedAt = new DateTime(2026, 1, 6, 17, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-29-44bd9a01-2f10-4b72-b910-a029",
                            Content = "Regression tests passed ✅",
                            CreatedAt = new DateTime(2026, 1, 6, 18, 30, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        },
                        new
                        {
                            Id = "post-30-2f8a91c2-18b4-4db9-b120-a030",
                            Content = "Refactoring legacy code feels great.",
                            CreatedAt = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = ""
                        });
                });

            modelBuilder.Entity("Instagram.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01",
                            Avatar = "/avatars/u1.png",
                            Bio = "Backend developer • ASP.NET • Linux",
                            CreatedAt = new DateTime(2024, 12, 1, 9, 10, 0, 0, DateTimeKind.Utc),
                            Email = "bozhidar@example.com",
                            Username = "bozhidar"
                        },
                        new
                        {
                            Id = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902",
                            Avatar = "/avatars/u2.png",
                            Bio = "Frontend dev • React",
                            CreatedAt = new DateTime(2024, 12, 3, 11, 20, 0, 0, DateTimeKind.Utc),
                            Email = "alex@example.com",
                            Username = "alex"
                        },
                        new
                        {
                            Id = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903",
                            Avatar = "/avatars/u3.png",
                            Bio = "UI / UX designer",
                            CreatedAt = new DateTime(2024, 12, 5, 15, 45, 0, 0, DateTimeKind.Utc),
                            Email = "maria@example.com",
                            Username = "maria"
                        },
                        new
                        {
                            Id = "c91e9189-281f-48c3-b8ad-1b20f4f10104",
                            Avatar = "/avatars/u4.png",
                            Bio = "Cybersecurity student",
                            CreatedAt = new DateTime(2024, 12, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nikola@example.com",
                            Username = "nikola"
                        },
                        new
                        {
                            Id = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105",
                            Avatar = "/avatars/u5.png",
                            Bio = "Digital artist",
                            CreatedAt = new DateTime(2024, 12, 7, 12, 40, 0, 0, DateTimeKind.Utc),
                            Email = "elena@example.com",
                            Username = "elena"
                        },
                        new
                        {
                            Id = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106",
                            Avatar = "/avatars/u6.png",
                            Bio = "DevOps • Docker • Kubernetes",
                            CreatedAt = new DateTime(2024, 12, 9, 8, 10, 0, 0, DateTimeKind.Utc),
                            Email = "ivan@example.com",
                            Username = "ivan"
                        },
                        new
                        {
                            Id = "e38db6c0-7b92-4f0f-b76a-d7b7f1aab107",
                            Avatar = "/avatars/u7.png",
                            Bio = "Game developer",
                            CreatedAt = new DateTime(2024, 12, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Email = "petar@example.com",
                            Username = "petar"
                        },
                        new
                        {
                            Id = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108",
                            Avatar = "/avatars/u8.png",
                            Bio = "Computer science student",
                            CreatedAt = new DateTime(2024, 12, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sofia@example.com",
                            Username = "sofia"
                        },
                        new
                        {
                            Id = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109",
                            Avatar = "/avatars/u9.png",
                            Bio = "Tech blogger",
                            CreatedAt = new DateTime(2024, 12, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Email = "george@example.com",
                            Username = "george"
                        },
                        new
                        {
                            Id = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110",
                            Avatar = "/avatars/u10.png",
                            Bio = "Marketing specialist",
                            CreatedAt = new DateTime(2024, 12, 14, 9, 20, 0, 0, DateTimeKind.Utc),
                            Email = "victoria@example.com",
                            Username = "victoria"
                        },
                        new
                        {
                            Id = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111",
                            Avatar = "/avatars/u11.png",
                            Bio = "Mobile developer",
                            CreatedAt = new DateTime(2024, 12, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            Email = "daniel@example.com",
                            Username = "daniel"
                        },
                        new
                        {
                            Id = "2df3b7c4-29c2-41b2-b2cb-51c8f20d8112",
                            Avatar = "/avatars/u12.png",
                            Bio = "QA engineer",
                            CreatedAt = new DateTime(2024, 12, 16, 11, 10, 0, 0, DateTimeKind.Utc),
                            Email = "teodora@example.com",
                            Username = "teodora"
                        },
                        new
                        {
                            Id = "4b46a84d-21a3-44db-9d2f-68c2f51f3113",
                            Avatar = "/avatars/u13.png",
                            Bio = "Java developer",
                            CreatedAt = new DateTime(2024, 12, 17, 10, 10, 0, 0, DateTimeKind.Utc),
                            Email = "martin@example.com",
                            Username = "martin"
                        },
                        new
                        {
                            Id = "5d7e09fa-b71a-44c5-9e1f-9b4e4b09f114",
                            Avatar = "/avatars/u14.png",
                            Bio = "Blockchain enthusiast",
                            CreatedAt = new DateTime(2024, 12, 18, 19, 30, 0, 0, DateTimeKind.Utc),
                            Email = "kaloyan@example.com",
                            Username = "kaloyan"
                        },
                        new
                        {
                            Id = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115",
                            Avatar = "/avatars/u15.png",
                            Bio = "Product manager",
                            CreatedAt = new DateTime(2024, 12, 19, 8, 50, 0, 0, DateTimeKind.Utc),
                            Email = "irina@example.com",
                            Username = "irina"
                        },
                        new
                        {
                            Id = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116",
                            Avatar = "/avatars/u16.png",
                            Bio = "Cloud engineer",
                            CreatedAt = new DateTime(2024, 12, 20, 12, 10, 0, 0, DateTimeKind.Utc),
                            Email = "stefan@example.com",
                            Username = "stefan"
                        },
                        new
                        {
                            Id = "bbcfb1c7-d4a6-46fa-a9cc-5c9df8d07117",
                            Avatar = "/avatars/u17.png",
                            Bio = "HR & recruiting",
                            CreatedAt = new DateTime(2024, 12, 21, 14, 15, 0, 0, DateTimeKind.Utc),
                            Email = "nadya@example.com",
                            Username = "nadya"
                        },
                        new
                        {
                            Id = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118",
                            Avatar = "/avatars/u18.png",
                            Bio = "Startup founder",
                            CreatedAt = new DateTime(2024, 12, 22, 17, 40, 0, 0, DateTimeKind.Utc),
                            Email = "rado@example.com",
                            Username = "rado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
